'------------------------------------------------------------------------------
' <auto-generated>
'     Este codigo foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SolicitacoesAtendimento.WebApplication.Pages

    Partial Public Class SolicitacaoList

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents lnkNovaSolicitacao As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents ddlPrioridade As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtNomeSolicitante As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtDataInicial As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnPesquisar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvSolicitacoes As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
