'------------------------------------------------------------------------------
' <auto-generated>
'     Este codigo foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SolicitacoesAtendimento.WebApplication.Pages

    Partial Public Class SolicitacaoUpdateStatus

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents lnkVoltar As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lnkDetalhes As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
        Protected WithEvents hfSolicitacaoId As Global.System.Web.UI.WebControls.HiddenField
        Protected WithEvents litTitulo As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litNomeSolicitante As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litStatusAtual As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litPrioridade As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents ddlNovoStatus As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtObservacao As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvHistorico As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
