'------------------------------------------------------------------------------
' <auto-generated>
'     Este codigo foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SolicitacoesAtendimento.WebApplication.Pages

    Partial Public Class SolicitacaoCreate

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents lnkVoltar As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
        Protected WithEvents vsErros As Global.System.Web.UI.WebControls.ValidationSummary
        Protected WithEvents txtTitulo As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvTitulo As Global.System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents txtDescricao As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvDescricao As Global.System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents txtNomeSolicitante As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents rfvNomeSolicitante As Global.System.Web.UI.WebControls.RequiredFieldValidator
        Protected WithEvents ddlPrioridade As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
