'------------------------------------------------------------------------------
' <auto-generated>
'     Este codigo foi gerado por uma ferramenta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SolicitacoesAtendimento.WebApplication.Pages

    Partial Public Class SolicitacaoDetails

        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        Protected WithEvents lnkVoltar As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lnkAtualizarStatus As Global.System.Web.UI.WebControls.HyperLink
        Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
        Protected WithEvents litId As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litTitulo As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litDescricao As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litNomeSolicitante As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litDataCriacao As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents litPrioridade As Global.System.Web.UI.WebControls.Literal
        Protected WithEvents gvHistorico As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
